/* This file is auto-generated by Payload. Run `npm run generate:types` after schema changes. */

export type User = {
  id: number;
  name?: string | null;
  role: "admin" | "editor" | "moderator";
  email: string;
  updatedAt: string;
  createdAt: string;
};

export type Media = {
  id: number;
  alt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  updatedAt: string;
  createdAt: string;
};

export type Post = {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: number | Media | null;
  content: Record<string, unknown>;
  status: "draft" | "published" | "scheduled";
  publishedAt?: string | null;
  pinned?: boolean | null;
  tags?: { tag?: string | null; id?: string | null }[] | null;
  updatedAt: string;
  createdAt: string;
};

export type HeroSlide = {
  id: number;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  sortOrder: number;
  isActive?: boolean | null;
  visibleFrom?: string | null;
  visibleUntil?: string | null;
  updatedAt: string;
  createdAt: string;
};
