/* This file is auto-generated by Payload. Run `npm run generate:types` after schema changes. */

export type User = {
  id: number;
  name?: string | null;
  role: "admin" | "editor" | "moderator";
  email: string;
  updatedAt: string;
  createdAt: string;
};

export type Member = {
  id: number;
  email: string;
  username: string;
  name: string;
  bio?: string | null;
  avatar?: number | Media | null;
  provider: "google" | "facebook";
  providerAccountId?: string | null;
  imageUrl?: string | null;
  country?: string | null;
  favoritePlayer?: string | null;
  joinedAt: string;
  updatedAt: string;
  createdAt: string;
};

export type MemberPost = {
  id: number;
  author: number | Member;
  body: string;
  images?: (number | Media)[] | null;
  createdAt: string;
  updatedAt: string;
};

export type MemberFollow = {
  id: number;
  follower: number | Member;
  following: number | Member;
  createdAt: string;
  updatedAt: string;
};

export type Media = {
  id: number;
  alt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  updatedAt: string;
  createdAt: string;
};

export type Post = {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: number | Media | null;
  content: Record<string, unknown>;
  status: "draft" | "published" | "scheduled";
  publishedAt?: string | null;
  pinned?: boolean | null;
  tags?: { tag?: string | null; id?: string | null }[] | null;
  updatedAt: string;
  createdAt: string;
};

export type HeroSlide = {
  id: number;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  sortOrder: number;
  isActive?: boolean | null;
  visibleFrom?: string | null;
  visibleUntil?: string | null;
  updatedAt: string;
  createdAt: string;
};

/** Nightly cricket snapshots (rankings, tours, squads, venues) — see sync:cricket */
export type CricketSnapshot = {
  id: number;
  key: string;
  label: string;
  fetchedAt: string;
  data:
    | Record<string, unknown>
    | {
        [k: string]: unknown;
      };
  updatedAt: string;
  createdAt: string;
};
